name: deploy node js to EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploying with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_CHANNELS_EC2_HOST }}
          username: ${{ secrets.SSH_CHANNELS_USERNAME }}
          key: ${{ secrets.CHANNELS_KEY }}
          port: 22
          script: |
            cd channels-backend
            git pull origin main
            whoami

